@startuml
    start

    if (Avengers Disassembled) then
        :The Sentry;
        :Spider-Woman: Origin;
        :New Avengers vol. 1;
        note right
            Avengers #500-503
            Avengers Finale
        end note

        :Avengers Disassembled: Iron Man, Thor & Captain America;
        :Secret War;

        :New Avengers vol. 1;
        note right: New Avengers #1-10

        :Young Avengers Omnibus;
        note right
            Young Avengers 1-12
            Young Avengers Special
        end note

        :Captain America Omnibus vol. 1;
        note right: Captain America #1-9

        :Pulse vol. 1;
        :Pulse vol. 2;
        
        :House of M Omnibus;
        :House of M Companion Omnibus;

        :Pulse vol. 3;
    
        detach

    elseif (Civil War) then
        :Sentry: Reborn;
        :Spider-Woman: Origin;
        :New Avengers vol. 2;
        
        :Captain America Omnibus vol. 1;
        note right: Captain America #11-21

        :Spider-Man by J. Michael Straczynski Omnibus vol. 1;
        :Spider-Man by J. Michael Straczynski Omnibus vol. 2;
        note right: Amazing Spider-Man #515-531;

        :Fantastic Four by J. Michael Straczynski;
        :Fantastic Four: The Life Fantastic;

        :Captain Marvel: Carol Danvers vol. 1;
        note right: issues #1-5

        :The Road to Civil War;
        :Civil War Prelude: New Warriors;
        :Civil War;
        :Civil War: Front Line;
        :Civil War: Iron Man;
        :Captain America Omnibus vol. 1;
        note right: Captain America #22-25
        :Civil War: Fantastic Four;
        :Young Avengers Omnibus;
        note right: Civil War: Young Avengers & Runaways #1-4
        :Spider-Man by J. Michael Straczynski Omnibus vol. 2;
        note right: Amazing Spider-Man #532-545;
        :Captain Marvel: Carol Danvers vol. 1;
        note right: issues #6-17

        detach

    elseif (Secret Invasion) then
        :New Avengers vol. 3;
        :Mighty Avengers by Brian Michael Bendis;
        note right: issues #1-12
        :Avengers: The Initiative vol. 1;
        note right: issues #1-13
        :Avengers/Invaders;
        :Captain America Omnibus vol. 2;
        :New Avengers vol. 4;
        note right: issue #38
        :Captain Marvel: Carol Danvers vol. 2;
        note right: issues #18-24
        :Secret Invasion Omnibus;
        :New Avengers vol. 4;
        note right: issues #50-54, Secret Invasion: Dark Reign
        :Avengers: The Initiative vol. 1;
        note right: issues #14-19, Annual #1
        :Young Avengers Omnibus;
        note right
            Young Avengers Presents #1-6
            Secret Invasion: Runaways/Young Avengers #1-3
        end note
        :Captain Marvel: Carol Danvers vol. 2;
        note right: issues #25-34;
        :Secret Invasion: Captain Marvel;
        :Captain America Omnibus vol. 3;
        
        detach

    elseif (Dark Reign / Siege) then
        :New Avengers: The Reunion;
        :Dark Avengers by Brian Michael Bendis;
        :Mighty Avengers by Dan Slott;
        :Avengers: The Initiative vol.2;
        note right: issues #20-30a
        :Spider-Woman: Agent of S.W.O.R.D.;
        :New Avengers vol. 5;
        note right: issues #55-60
        :Siege;
        :Avengers: The Initiative vol. 2;
        note right: issues #31-35
        :Avengers vol. 5;
        note right: issues #61-64
        :Young Avengers Omnibus;
        note right
            Dark Reign: Young Avengers #1-5
            Siege: Young Avengers #1
        end note
        :Captain Marvel: Carol Danvers vol. 3;

        detach

    elseif (Fear Itself) then
        :Avengers vol. 1;
        :Secret Avengers by Ed Brubaker;
        :New Avengers vol. 7;
        note right: issues #1-13
        :Young Avengers Omnibus;
        note right
            Avengers: the Children’s Crusade #1-9
            Avengers: The Children’s Crusade - Young Avengers #1
        end note
        :Avengers Academy vol. 1;
        :Captain America Omnibus vol. 4;
        :Fear Itself;
        :New Avengers vol. 7;
        note right: issues #14-23;
        :Avengers vol. 2;
        :Fear Itself: Secret Avengers;
        :Secret Avengers: Run the Mission, Don't Get Seen, Save the World;
        :Avengers Academy vol. 2;
        :Captain America Omnibus vol. 5;
        :Iron Man 2.0 vol. 1;
        :Iron Man 2.0 vol. 2;

        detach

    elseif (Avengers vs. X-Men) then
        :Avengers vol. 3;
        note right: Avengers Assemble #1-8
        :Secret Avengers by Rick Remender;
        note right: issues #22-25
        :Avengers Vs X-Men Omnibus;
        :Avengers vol. 3;
        note right: issues #31-34
        :New Avengers vol. 7;
        note right: issues #31-34
        :Avengers Academy;
        note right: issues #34-39
        :Secret Avengers by Rick Remender;
        note right: issues #29-37
        :Battle Scars;

        detach

    elseif (Hickman) then
        :Secret Warriors Omnibus;
        :S.H.I.E.L.D.: Architects of Forever;
        :S.H.I.E.L.D.: The Human Machine;
        :Fantastic Four by Jonathan Hickman Omnibus vol. 1;
        :Fantastic Four by Jonathan Hickman Omnibus vol. 2;
        :Ultimate Marvel by Jonathan Hickman Omnibus;
        :Avengers Assemble: Science Bros.;
        :Age of Ultron: The Complete Event;
        :Captain Marvel by Kelly Sue Deconnick Omnibus;
        note right
            Captain Marvel (2012) issues #1-14
            Avengers Assemble issues #16-17
        end note

        :Avengers by Jonathan Hickman Omnibus vol. 1;
        :Captain Marvel by Kelly Sue Deconnick Omnibus;
        note right
            Captain Marvel (2012) issues #15-17
            Avengers Assemble issues #18-19
        end note
        :Avengers Assemble #20;
        :Captain Marvel by Kelly Sue Deconnick Omnibus;
        note right: Captain Marvel (2014) issues #1-15
        :Avengers Assemble: The Forgeries Of Jealousy;
        :Captain America by Rick Remender Omnibus;
        :Original Sin;
        :Avengers by Jonathan Hickman Omnibus vol. 2;
        :Secret Wars: Last Days of the Marvel Universe;
        :Secret Wars;
        :Secret Wars - Battleworld titles;
        :Secret Wars - Warzones titles;

        detach
    else
        stop
    endif

@enduml
